plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.143'
}

version = '1.1.0'
group = 'dev.skogrine.mixinfix'
base.archivesName = 'mixinfix'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

repositories {
    mavenCentral()
}

neoForge {
    version = '21.1.235'
    mods {
        mixinfix {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly 'io.github.llamalad7:mixinextras-common:0.4.1'
    annotationProcessor 'io.github.llamalad7:mixinextras-common:0.4.1'
}
